"""add clarification_rules

Revision ID: 6c245d5ff842
Revises: fa29aa32d2a7
Create Date: 2026-02-03 12:41:38.613457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c245d5ff842'
down_revision = 'fa29aa32d2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clarification_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_prompts', schema=None) as batch_op:
        batch_op.drop_column('clarification_rules')
    # ### end Alembic commands ###

