
"""empty message

Revision ID: 7005c89eb4c0
Revises: 7352514e3c15
Create Date: 2026-02-25 12:00:24.490470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7005c89eb4c0'
down_revision = '7352514e3c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_user_id', sa.String(length=64), nullable=False),
    sa.Column('part_number', sa.String(length=255), nullable=True),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_search_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_part_search_logs_item_description'), ['item_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_search_logs_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_part_search_logs_whatsapp_user_id'), ['whatsapp_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part_search_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_part_search_logs_whatsapp_user_id'))
        batch_op.drop_index(batch_op.f('ix_part_search_logs_part_number'))
        batch_op.drop_index(batch_op.f('ix_part_search_logs_item_description'))

    op.drop_table('part_search_logs')
    # ### end Alembic commands ###
