"""empty message

Revision ID: 7352514e3c15
Revises: 876757e1d484
Create Date: 2026-02-24 15:53:39.377964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7352514e3c15'
down_revision = '876757e1d484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_vin_search', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('success_vin_search', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('failed_vin_search', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('current_vin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_vin', mysql.CHAR(collation='utf8_unicode_ci', length=17), nullable=True))
        batch_op.drop_column('failed_vin_search')
        batch_op.drop_column('success_vin_search')
        batch_op.drop_column('total_vin_search')
    # ### end Alembic commands ###
