"""Add vip_numbers to IntentPrompt

Revision ID: 876757e1d484
Revises: 6c245d5ff842
Create Date: 2026-02-04 11:17:47.978152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '876757e1d484'
down_revision = '6c245d5ff842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_numbers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_prompts', schema=None) as batch_op:
        batch_op.drop_column('vip_numbers')
    # ### end Alembic commands ###