"""init_tables

Revision ID: b805b54ebc48
Revises: 
Create Date: 2025-11-04 21:14:55.452657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b805b54ebc48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_user_id', sa.String(length=64), nullable=False),
    sa.Column('user_locale', sa.String(length=16), nullable=True),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('assigned_agent', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_whatsapp_user_id'), ['whatsapp_user_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.String(length=16), nullable=True),
    sa.Column('chassis_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_chassis_number'), ['chassis_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicles_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_year'), ['year'], unique=False)

    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_min', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parts_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parts_part_number'), ['part_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parts_part_number'))
        batch_op.drop_index(batch_op.f('ix_parts_name'))
        batch_op.drop_index(batch_op.f('ix_parts_brand'))

    op.drop_table('parts')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_year'))
        batch_op.drop_index(batch_op.f('ix_vehicles_model'))
        batch_op.drop_index(batch_op.f('ix_vehicles_make'))
        batch_op.drop_index(batch_op.f('ix_vehicles_chassis_number'))

    op.drop_table('vehicles')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_whatsapp_user_id'))

    op.drop_table('leads')
    # ### end Alembic commands ###
